local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>fa', builtin.find_files, {}, { desc = "search all files" })
vim.keymap.set('n', '<leader>ff', builtin.git_files, {}, { desc = "search git tracked files" })
vim.keymap.set('n', '<leader>fg', builtin.live_grep, {}, { desc = "search with live grep" })
vim.keymap.set('n', '<leader>fb', builtin.buffers, {}, { desc = "search buffers" })
vim.keymap.set('n', '<leader>fh', builtin.help_tags, {}, { desc = "search help tags" })
vim.keymap.set('n', '<leader>gs', function() 
	builtin.grep_string({ search = vim.fn.input("Grep > ") })
end, { desc = "grep for string" })
